# Sudo required for doing docker build
sudo: required
services:
- docker

# Build the docker image
script:
- ./build/docker-build.sh

# If successful, see if we need to publish also
after_success:
- ./build/travis-publish.sh

# Environment variables needed when publishing
env:
  global:
  # DOCKER_USER
  - secure: "B8BLh4OzoR519q98ZPQV/K4sHknKHBsm/KBIB7HWP/ypeIkxwM2kmvpJ7ceOwvOVmt6R4H66D+4FaYp1Eh3l0LH8KJJNGiNCc72cHCqUOFaABLYLX3cKriE9RRgwPN5QTJMbpOB1jJYmX9d7sRmJ5i/UYE105jd5bRPZe19NficWx9EKzsefEZZbs1rZCuNOkOJsgnZ3yABgrzl56tGarYik7n4H/nUpAidrdnsVabj4rqRqYlUb3E0Kyn5OP1X77udCvZP9X/xzLvIfeKTaS0TNdu89ArTWKeA53JF9lThNU5kAjfYSUVwSBj/4T1SMdZB4LBW32pDI5KW+PB1UIpBVu3uRQmdM2k9YvO9fqJCHl/XTUc5gDNcFCsoXilIm5an3+RM0cp2xAX88G3dlqhA715B/bdM64yj5uNssM5sCJu6sdQnPOYNG1nwuLfc5NwpONVOrwT5/YsB7r++gfGnjEFdEJ9hZAHh7QzyKhrurYgFG6OcWnjdWzAQUqHGv1SetCUEmAAcgCKSjBkDCKGZBxFmGzYZB5d/vLVC/T6sa2tprXVgemD4do4WVkx0AQQAo0qpiX+vF+kLZm9dthCeIMipL2jgtsVcEp/+7tO5ttq0yHcWSXeR1WihuVPadATQt/ISvleibLITVRt7VRag8m++bLl0laC3ICsYnHIQ="
  # DOCKER_EMAIL
  - secure: "qJtjT2dj92RIreAqMF7JZZiYlLoFwnECwlHRQHkCbZ+hfpm0bq0LkQifs5gH/w7S0TZgNVND9yyFZSgDjoTym2I3ucFxjTFiB1OB2sVTthOxg445vz1/Ye5YrRIC7i4M2bz07ObW+mV4+o7kPzVN/sKG/jXC0GDfN6YLUTG0fdFfeMP90rgGIPh6y997pX0HwSYIrCnC7eLgbuMeZF3r7aVF1erjhfh5zLcESe5OTuYCIJsHBW2oC/GjMe4ItYCFgZvRszeglsJ6mj2498G2DxSHkBncYW4jKhv7thpiD3WOWrDLcTEGGFhHLTLNLNLKibgfwpbkhvNmmzrzZ7JEesV8NBA4QCO7p+lskwICwdD+VGVS5ZAI4FijSs5EiOxmgoeiHTRmdc5QUXw9Kqz3y4+yMvW0D4/GhRu7/EK6hy3SiFW1UK2ZidwyTppT+y6RSTDbG+68ddLym56oVBzt4g/1nZhSq4ION0VTqCrNnnQBmJ4nMf1I/zfJ1r38XMHFY9bcTVeg6aQm8kRNZL7HQg6d3kr9vhD2k3HJBC9YS+Quh5Wc0/h2mMR3f9bnWGWNPCOkTbGk5KiXn2OXHRW4EmiKscV7BFMpnDSN7MgbkpxZIHezrdM9e+Iu12IsnkKab5puyg7d9P8RQ68SGIhQqlW7sRTMFYKTgLdEcrRyNwQ="
  # DOCKER_PASS
  - secure: "Lx+TvlZDWpqeLi5a96vl1hT4y8RrJj1kMzASh0fEmBU1xIcc/XEBBDqIDFSZ7AGZYMQTU0kZ15fyCbjntsW+Lxus0Dpiyh65E2iVSnaZJIsvawi0NxaZ4Zf15m1Lks5fYjGaJopjSNSs/SjEiTjhwu20Ko8spQiHDwuEgFc5PnV2t52uJQJP0oYW8Hf4OOugPHMvq3cpMtG4FFNeiSY75AR5JUBjMb7wznrdUwJgZTZvdg9HkWT7AS7Yc0EWoYlA4s5irvNCp3OBHF0cRMZTmdkYfZjpeMVo5bYkCOWV+6YnII3ickzDPAB1gZIDnPxwQ90Xhvw5aDpvS/3Cv8aWxEQFXqs+YVka2HTiEqralbTHvUaOf8zo7K4IcSUU5n8qqrQnFuWMlpiSeA6ZrBzzpLuwrvapwRllT6xfIncOz/S6+t6aS8e6kbOE6Vk+1/2wF8bRd9qylzwIA1diwyIF2SWfL3+GNXsp0Oe3RikZP6CAJa/iJte2lau/RzzYcXbzyAuDJ+bXnY7pYWUy9v568ZVhvt5Xn75w+e2tBGR64xAjRGKPiovODLYcV5The1xOhQQ0ughRIk+4e78AugFv5TOM+c+ZOyQ+ImD8MVSx96/lmRrtlAltAAxgd8uOldXat9TJiYDplrb+eQ25aEJIEHN1f9Z9nl8X7gaSTUqA/VA="
